FROM tinkerpop/gremlin-server:3.4.6

WORKDIR /opt/gremlin-server

ADD conf/server/my-tinkergraph.properties conf/my-tinkergraph.properties
ADD conf/server/my-gremlin-server.yaml conf/my-gremlin-server.yaml
